let PizzaList = [
  {
    id: 1,
    name: "Genissis",
    img: "images/01.png",
    prices: [560.0, 562.0, 563.89],
    sizes: ["30", "40", "42"],
    description:"Produto Original, importado dos EUA. 🤤",
  },
  {
    id: 2,
    name: "Jordan MID",
    img: "images/jordan1mid.png",
    prices: [500.0, 502.0, 503.50],
    sizes: ["32", "40", "42"],
    description: "Produto Original, importado dos EUA. 🤤",
  },
  {
    id: 3,
    name: "Jordan Phat",
    img: "images/jordanPhat1.png",
    prices: [710.0, 712.0, 713.45],
    sizes: ["34", "41", "43"],
    description:"Produto Original, importado dos EUA. 🤤",
  },
  {
    id: 4,
    name: "Launch White",
    img: "images/launch.png",
    prices: [400.0, 403.0, 404.77],
    sizes: ["32", "39", "43"],
    description:"Produto Original, importado dos EUA. 🤤",
  },
  {
    id: 5,
    name: "Jordan Old Love",
    img: "images/oldLove.png",
    prices: [610.0, 612.0, 614.43],
    sizes: ["33", "40", "43"],
    description:"Produto Original, importado dos EUA. 🤤",
  },
  {
    id: 6,
    name: "Jordan Rebelxx",
    img: "images/rebelxx.png",
    prices: [720.50, 722.0, 724.0],
    sizes: ["36", "41", "43"],
    description:"Produto Original, importado dos EUA. 🤤",
  },
  {
    id: 7,
    name: "Jordan Retro",
    img: "images/retroHigh.png",
    prices: [550.0, 551.50, 553.0],
    sizes: ["37", "40", "43"],
    description:"Produto Original, importado dos EUA. 🤤",
  },
  {
    id: 8,
    name: "Jordan Rebelxx",
    img: "images/rebelxx.png",
    prices: [720.50, 722.0, 724.0],
    sizes: ["36", "41", "43"],
    description:"Produto Original, importado dos EUA. 🤤",
  },
  {
    id: 9,
    name: "Jordan Retro",
    img: "images/retroHigh.png",
    prices: [550.0, 551.50, 553.0],
    sizes: ["37", "40", "43"],
    description:"Produto Original, importado dos EUA. 🤤",
  },
];
